server:
  port: 8080

spring:
  datasource:
    username: searchUser
    password: search_User
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://ipfran.ru/
#      name: ИПФРАН
#    - url: https://nikoartgallery.com/
#      name: Nico
#    - url: https://dombulgakova.ru
#      name: BulgakovsHome
#    - url: https://www.svetlovka.ru
#      name: Svetlovka
    - url: https://volochek.life/
      name: Портал Вышнего Волочка

