server:
  port: 8088

compose:
  phpMyAdmin:
    port: 8086

spring:
  datasource:
    url: jdbc:mysql://root:search_User@localhost:3307/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:p6spy:mysql://localhost:3307/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
