services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: search_User
      MYSQL_DATABASE: search_engine
    ports:
      - 3307:3306
    volumes:
      - search-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8086:80
    depends_on:
      - db

volumes:
  search-volume: